### PR TITLE
Refs #221 adding compare option

### PR DESCRIPTION
**Pull request by pedrofs**
It is a starting point for solving #221 

@ravage84 is something like this you were expecting?

### CODE REVIEW

**Comment by ravage84** [comment]
Sorry, I simply had no time to check it thoroughly, yet.

**Comment by ravage84** [comment]
Doesn't the question now gets asked twice?

1. https://github.com/CakeDC/migrations/pull/265/files#diff-37474b3b4f16c4557426ae2098d43cfdR440 (if ``--compare`` is not set)
2.  https://github.com/CakeDC/migrations/pull/265/files#diff-37474b3b4f16c4557426ae2098d43cfdR443 (always)

**Comment by pmoraes** [comment]
Hi @ravage84 I have removed this command in this commit https://github.com/CakeDC/migrations/pull/273/commits/56e76b7f943521ece3cb72fff238ce4a26c2d0f2

**Comment by pmoraes** [comment]
hi @ravage84, this changes made by @pedrofs, they are what were you expecting?

**Pull request merged**
