### PR TITLE
removing reserved word (String) from MigrationShell

### PR DESCRIPTION
**Pull request by begnini**
These modifications are the only things I found to make Migrations Plugin compatible with PHP 7.

### CODE REVIEW

**Comment by omnuvito** [comment]
Hi @begnini, In the file there are two words reserved for change on lines 908 and 920, with these changes your PR will be ready to merge. Thanks.

**Comment by adrien-louis-r** [comment]
Hi, we have made a fork containing this fix. You can fetch this branch : https://github.com/occitech/migrations/tree/string-keyword-php7.

I can open an other PR if needed.

**Comment by omnuvito** [comment]
Hi @adrien-louis-r, you could make a new PR with the new changes. This should be done into develop branch. Thanks.

**Comment by omnuvito** [comment]
Thanks @begnini, your changes were merged in PR #258.

**Pull request closed without merging**
