### PR TITLE
Match requirement in readme

### PR DESCRIPTION
**Pull request by xhs345**

### CODE REVIEW

**Comment by pmoraes** [comment]
Hi @xhs345  did you have some issue with php 5.2.8 update the documentation?

**Comment by xhs345** [comment]
Just thought it would be confusing if it suggests a different minimum PHP version in the Readme.md

**Comment by pmoraes** [comment]
@xhs345  Where is different? could you show me this difference? 

Thanks.

**Comment by xhs345** [comment]
Sure, this is the relevant change in the readme: https://github.com/CakeDC/migrations/commit/5837a30af14122dbe74c5cf509439d454bdaa275
and it was part of the recent updated to tag version 2.5.0. The current composer.json still references the older PHP requirement (https://github.com/CakeDC/migrations/blob/master/composer.json#L24)

**Comment by pmoraes** [comment]
@xhs345 ok, Thanks.

**Comment by pmoraes** [comment]
Merged

**Pull request merged**
